export enum ListRoles {
	ROLE_TYPE_ADMIN = 'admin',
	ROLE_TYPE_USER = 'user',
	
 	ROLE_ADMIN = 'ROLE_ADMIN',
	ROLE_SUPER_USER = 'ROLE_SUPER_USER',
	ROLE_USER = 'ROLE_USER',

	ROL_ADMIN = 'ROL_00000000',
	ROL_USER = 'ROL_00000006',
};


export enum UserTypeEnum {
	SUPER_ADMIN = 'SUPER_ADMIN',
	CUSTOMER = 'CUSTOMER',
	ADMIN = 'ADMIN',
	WORKSPACE_ADMIN = 'WORKSPACE_ADMIN',
	EMPLOYEE = 'EMPLOYEE',
	SHOP_MANAGER = 'SHOP_MANAGER',
	TECHNICIAN = 'TECHNICIAN',
	DELIVERER = 'DELIVERER',
};


export enum CountryEnum {
	FRANCE = 'FRANCE',
	BELGIUM = 'BELGIUM',
	SWITZERLAND = 'SWITZERLAND',
	CANADA = 'CANADA',
	SPAIN = 'SPAIN',
	ITALY = 'ITALY',
	GERMANY = 'GERMANY',
	PORTUGAL = 'PORTUGAL',
	UNITED_KINGDOM = 'UNITED_KINGDOM',
	UNITED_STATES = 'UNITED_STATES',
};

